apiVersion: apps/v1
kind: Deployment
metadata:
  name: dd-suitcase-controller
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dd-suitcase-controller
  template:
    metadata:
      annotations:
        prometheus.io/scrapehttps: 'true'
        prometheus.io/path: /metrics
        prometheus.io/port: '443'
      labels:
        app: dd-suitcase-controller
    spec:
      containers:
      - name: dd-suitcase-controller
        image: 150.214.150.155:5000/dd-suitcase-controller:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 100m
---
apiVersion: v1
kind: Service
metadata:
  name: dd-suitcase-controller-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
    app: dd-suitcase-controller
  ports:
  - protocol: TCP
    port: 443
    targetPort: 443
    nodePort: 30011
    name: https

  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30012
    name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dd-suitcase-dh
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dd-suitcase-dh
  template:
    metadata:
      annotations:
        prometheus.io/scrapehttps: 'true'
        prometheus.io/path: /metrics
        prometheus.io/port: '8063'
      labels:
        app: dd-suitcase-dh
    spec:
      containers:
      - name: dd-suitcase-dh
        image: 150.214.150.155:5000/dd-suitcase-dh:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 100m
---
apiVersion: v1
kind: Service
metadata:
  name: dd-suitcase-dh-entrypoint
  namespace: default
spec:
  selector:
    app: dd-suitcase-dh
  ports:
  - protocol: TCP
    port: 8063
    targetPort: 8063
  type: ClusterIP
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: dd-suitcase-controller
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dd-suitcase-controller
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: dd-suitcase-dh
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dd-suitcase-dh
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
